name: made_with_flutter
description: Made with Flutter is an open source tool that lets you know if an APK/APP was made with Flutter or not.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_builder: ^0.6.4
  dotted_border: ^2.0.0+3
  url_launcher: ^6.1.10
  lottie: ^2.3.0
  animated_text_kit: ^4.2.2
  flutter_bloc: ^8.1.2
  flutter_dropzone: ^3.0.5
  archive: ^3.3.6
  elegant_notification: ^1.8.1
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
